### PR TITLE
Folge 4: Images bauen

### PR DESCRIPTION
**Pull request by StefanScherer**
Hi @goloroden,
hier ist noch der Beispielcode für Folge 4: Images bauen

Der PR basiert auf #6, da ich im obersten README.md in beiden PR's etwas geändert habe.

### CODE REVIEW

**Review by goloroden — APPROVED** [review]

**Comment by StefanScherer** [comment]
I've rebased the PR due to a conflict. 
@goloroden PTAL :-)

**Review by goloroden — COMMENTED** [review]
Hi @StefanScherer 👋 

Thanks for this PR! Basically, it looks good, and I assume it suits your needs – however, a few things caught my eye, and I at least wanted to ask whether they should stay this way:

- You're using pretty old JavaScript keywords, such as `var` (instead of `let` and `const`). Is this by intention (to keep things as simple as possible)?
- In the `package.json` files, the dependencies are using the `~` character to define ranges. In practice, this is often a bad idea, so I wanted to ask whether this should stay this way?

Since this course is about Docker, not Node.js, I'm fine with whatever your answer is, as said, they just caught my eye from a Node.js developer's point of view.

What do you think?

**Comment by StefanScherer** [comment]
Hi @goloroden Thanks for the quick review.
Maybe it's better to watch the video first. The code example is the unmodified output of `npx express-generator`. Maybe we should raise your concerns upstream 😅
It's not a Node.js course, it's just code and I want to offer the audience to see the sources as it was created in the video.
WDYT?

**Comment by goloroden** [comment]
Sounds perfectly reasonable, and I wasn't aware of the fact that the code is generated, so all is good 👍

**Review by goloroden — APPROVED** [review]

**Pull request merged**
